# Generated by Django 2.2.6 on 2019-11-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('room_image', models.ImageField(default='images/roomCategories/none.png', upload_to='images/roomCategories')),
                ('price', models.IntegerField()),
                ('total_rooms', models.IntegerField()),
            ],
        ),
    ]
