# Generated by Django 2.2.6 on 2019-11-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name': 'Room Category', 'verbose_name_plural': 'Room Categories'},
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
