# Generated by Django 2.2.6 on 2019-11-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='nbr_of_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
